-- Base schema for amused-to-death (Postgres).
--
-- This is the DbUp base migration and the single source of truth for a fresh
-- database. It is written to be IDEMPOTENT so it can run safely against BOTH a
-- brand-new empty database AND the existing Neon database (which has been
-- brought in line with these names via the one-off rename script — see
-- migration/rename-to-best-practice.sql). On the existing DB every statement
-- here is a no-op that simply records 0001 as applied.
--
-- Naming conventions:
--   * snake_case everywhere (no quoted camelCase identifiers).
--   * created_at / updated_at timestamps (updated_at maintained by a trigger).
--   * boolean flags (not MySQL BIT).
--   * identity columns for surrogate keys.
--
-- Later schema changes go in new numbered scripts (0002_*.sql, ...); never edit
-- this file after it has been applied anywhere.

CREATE TABLE IF NOT EXISTS characters (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ilvl        integer      NOT NULL DEFAULT 0,
    main        integer,
    name        varchar(30)  NOT NULL,
    class       integer      NOT NULL,
    realm       varchar(50)  NOT NULL DEFAULT 'stormscale',
    role_tank   boolean      NOT NULL DEFAULT false,
    role_heal   boolean      NOT NULL DEFAULT false,
    role_dps    boolean      NOT NULL DEFAULT false,
    hidden      boolean      NOT NULL DEFAULT false,
    raider      boolean      NOT NULL DEFAULT false,
    vip         boolean      NOT NULL DEFAULT false,
    discord     varchar(50),
    created_at  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT characters_main_fkey FOREIGN KEY (main) REFERENCES characters(id)
);

CREATE TABLE IF NOT EXISTS raids (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(50),
    gold        integer       NOT NULL DEFAULT 0,
    paid        boolean       NOT NULL DEFAULT false,
    comment     varchar(2000),
    created_at  timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS applications (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edit_token        varchar(18)  NOT NULL,
    name              varchar(50),
    server            varchar(50),
    battle_tag        varchar(250),
    spec              varchar(250),
    ui_screenshot_url varchar(250),
    reason            text,
    history           text,
    alts              text,
    created_at        timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       varchar(26),
    username    varchar(50),
    expires_at  timestamp    NOT NULL
);

CREATE TABLE IF NOT EXISTS attendance (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id integer     NOT NULL,
    raid_id      integer     NOT NULL,
    bosses       integer     NOT NULL,
    paid         boolean     NOT NULL DEFAULT false,
    created_at   timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT attendance_character_fkey FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE,
    CONSTRAINT attendance_raid_fkey      FOREIGN KEY (raid_id)      REFERENCES raids(id)      ON DELETE CASCADE,
    CONSTRAINT attendance_raid_char_uniq UNIQUE (raid_id, character_id)
);

-- updated_at auto-maintenance trigger (replaces MySQL's ON UPDATE CURRENT_TIMESTAMP).
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- CREATE TRIGGER has no IF NOT EXISTS, so guard each with a catalog check.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_characters_updated_at') THEN
        CREATE TRIGGER trg_characters_updated_at BEFORE UPDATE ON characters
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_raids_updated_at') THEN
        CREATE TRIGGER trg_raids_updated_at BEFORE UPDATE ON raids
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_applications_updated_at') THEN
        CREATE TRIGGER trg_applications_updated_at BEFORE UPDATE ON applications
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_attendance_updated_at') THEN
        CREATE TRIGGER trg_attendance_updated_at BEFORE UPDATE ON attendance
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    END IF;
END $$;
