-- Application revision history.
--
-- Turns `applications` from a single mutable row per applicant into an identity
-- row plus an append-only stream of immutable snapshots in
-- `application_versions`. The applicant still edits via their edit_token and only
-- ever sees the latest state; logged-in reviewers can browse every revision and
-- diff any two.
--
-- Design:
--   * application_versions holds a FULL snapshot of the editable fields per
--     version (not deltas) — simplest and correct for 8 short text fields.
--   * version_no is a per-application counter starting at 1.
--   * applications.current_version_id points at the latest snapshot for O(1)
--     "latest" reads. It is nullable only transiently during insert; every
--     application ends up pointing at a version.
--   * Snapshots are INSERT-only. Nothing ever UPDATEs an application_versions row,
--     which is what makes the history trustworthy.

CREATE TABLE IF NOT EXISTS application_versions (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id    integer      NOT NULL,
    version_no        integer      NOT NULL,
    name              varchar(50),
    server            varchar(50),
    battle_tag        varchar(250),
    spec              varchar(250),
    ui_screenshot_url varchar(250),
    reason            text,
    history           text,
    alts              text,
    created_at        timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT application_versions_application_fkey
        FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE,
    CONSTRAINT application_versions_unique_no UNIQUE (application_id, version_no)
);

CREATE INDEX IF NOT EXISTS idx_application_versions_application
    ON application_versions (application_id);

-- Latest-version pointer on the identity row.
ALTER TABLE applications
    ADD COLUMN IF NOT EXISTS current_version_id integer;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'applications_current_version_fkey'
    ) THEN
        ALTER TABLE applications
            ADD CONSTRAINT applications_current_version_fkey
            FOREIGN KEY (current_version_id) REFERENCES application_versions(id);
    END IF;
END $$;

-- Backfill: every existing application becomes version 1 carrying its current
-- field values, and its current_version_id is pointed at that snapshot. Guarded
-- so a re-run (or a run against a DB where this already happened) is a no-op.
INSERT INTO application_versions
    (application_id, version_no, name, server, battle_tag, spec, ui_screenshot_url, reason, history, alts, created_at)
SELECT a.id, 1, a.name, a.server, a.battle_tag, a.spec, a.ui_screenshot_url, a.reason, a.history, a.alts, a.created_at
FROM applications a
WHERE NOT EXISTS (
    SELECT 1 FROM application_versions v WHERE v.application_id = a.id
);

UPDATE applications a
SET current_version_id = v.id
FROM application_versions v
WHERE v.application_id = a.id
  AND v.version_no = 1
  AND a.current_version_id IS NULL;
